### ISSUE TITLE
Add continuous integration builds

### ISSUE THREAD

**Issue by mightea** [swisscom/sdx#3]
We d like to add a CI build to the project using travis-ci.org. As I do not have the required permissions to authorize travis-ci to access this public project it would be appreciated if someone with the appropriate privileges could perform this task. 

![travis-ci](https://cloud.githubusercontent.com/assets/3684954/15820730/8d2d5eec-2beb-11e6-99e5-2d97d2ac1840.png)

Maybe @mastertinner ?

**Comment by mastertinner** [comment]
Good idea. I enabled Travis.
