### ISSUE TITLE
Enable Greenkeeper

### ISSUE THREAD

**Issue by mastertinner** [swisscom/sdx#4]
Since we have Travis enabled now, I think it would also make sense to enable [Greenkeeper](https://greenkeeper.io/). What do you guys think?

**Comment by mightea** [comment]
Good idea, even better than david we use currently!

**Comment by mightea** [comment]
it seems like we need your help again @mastertinner 

```sh
$ greenkeeper enable
🌴  info enable The GitHub slug is: swisscom/sdx
🌴  ERR! enable Admin access is required to enable a repository.
🌴  ERR! enable Please ask an admin on your team to enable Greenkeeper.
```

**Comment by mastertinner** [comment]
Thanks, @mightea. I just wanted to confirm with you guys before enabling it. Now it's enabled.
